//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyRestfullApp.Data
{
    using System;
    using System.Collections.Generic;

    public partial class User
    {
        #region Properties

        public string apellido
        {
            get; set;
        }

        public string email
        {
            get; set;
        }

        public int id
        {
            get; set;
        }

        public string nombre
        {
            get; set;
        }

        public string password
        {
            get; set;
        }

        #endregion Properties
    }
}